# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = ["model.py"]

doc_url = "https://NuuttiSten.github.io/ml_project_template_test_nuutti/"

git_url = "https://github.com/NuuttiSten/ml_project_template_test_nuutti/tree/master/"

def custom_doc_links(name): return None
